import { useI18n } from '../i18n/I18n.js';
import { Icon } from './Panels.js';

export function HelpContent({ busy, onStart }: { busy: boolean; onStart: () => void }) {
  const { locale } = useI18n();
  if (locale === 'en-US') return <div className="help-content">
    <section className="help-hero" aria-labelledby="help-intro-en"><div><h3 id="help-intro-en">Your first flight in three steps</h3><p>Load real orders, review a route, then dispatch. The simulation always checks capacity, range, funds, energy, and airport level.</p></div><button className="start-guide-help" disabled={busy} onClick={onStart}>Start Guided Tutorial</button></section>
    <div className="help-grid">
      <section className="help-card help-steps"><header><Icon name="airport"/><h3>Quick Start</h3></header><ol><li><b>1</b><span><strong>Load at the airport</strong><small>Select traffic on the apron to load it into the cutaway cabin; select it inside to unload. An order that does not fit is skipped as a whole.</small></span></li><li><b>2</b><span><strong>Plan in order</strong><small>Open Plan Route and review each leg’s time, cost, income, and energy before dispatch.</small></span></li><li><b>3</b><span><strong>Arrive and transfer</strong><small>Only final-destination orders pay. Other orders remain aboard or can be unloaded for a later connection.</small></span></li></ol></section>
      <section className="help-card"><header><Icon name="map"/><h3>Globe Map</h3></header><ul><li><strong>Map</strong><span>Browse cities, inspect airports, and unlock new stops without changing a route.</span></li><li><strong>Controls</strong><span>Drag to rotate; use the wheel or pinch to zoom. Arrow keys rotate, +/− zoom, and Home locates the current aircraft.</span></li><li><strong>Visibility</strong><span>Back-side airports are hidden on the globe; the city picker remains available for every airport.</span></li></ul></section>
      <section className="help-card"><header><Icon name="plane"/><h3>Operations</h3></header><ul><li><strong>Fleet Management</strong><span>View flights, switch aircraft, refit, recharge energy, and manage turnaround.</span></li><li><strong>Company Organization</strong><span>Recruit staff, assign posts and managers, train employees, and review records.</span></li><li><strong>Company Operations</strong><span>Claim goals and daily rewards, then manage logistics, services, facilities, research, trade, and the museum.</span></li></ul></section>
      <section className="help-card help-resources"><header><Icon name="ticket"/><h3>Resources & Settlement</h3></header><dl><div><dt>Operating funds</dt><dd>Earned from delivered orders and operations; spent on flights, aircraft, airports, and services.</dd></div><div><dt>Tickets</dt><dd>A scarce resource earned from paid flights, goals, daily progress, and museum donations; used by staffing and advanced operations.</dd></div><div><dt>Time</dt><dd>Arrivals settle as time events, never from animation callbacks. Offline progress is capped at 8 hours.</dd></div></dl></section>
    </div>
    <aside className="help-rule-strip"><strong>Remember:</strong><span>Route previews are read-only. Every order pays once at its final destination. Aircraft and economic values are game configurations; the globe is not navigation or administrative-boundary data.</span></aside>
    <p className="muted-text">Map aircraft: <a href="https://sketchfab.com/3d-models/low-poly-airliner-f06d488f08764e3ca26f2917d4053c69" target="_blank" rel="noreferrer">Low Poly Airliner by Mauro3D</a> · <a href={`${import.meta.env.BASE_URL}models/ATTRIBUTION.txt`} target="_blank" rel="noreferrer">CC BY 4.0 — credits and modifications</a></p>
  </div>;
  return <div className="help-content">
    <section className="help-hero" aria-labelledby="help-intro-zh"><div><h3 id="help-intro-zh">首航三步</h3><p>先装载真实订单，再核对路线，最后起飞。容量、航程、资金、能量和机场等级始终由经营核心校验。</p></div><button className="start-guide-help" disabled={busy} onClick={onStart}>开始分步引导</button></section>
    <div className="help-grid">
      <section className="help-card help-steps"><header><Icon name="airport"/><h3>快速开始</h3></header><ol><li><b>1</b><span><strong>在机场装载</strong><small>点击地面客货装入剖视机舱，点击舱内客货卸载；容量不足时跳过整单，不会拆分订单。</small></span></li><li><b>2</b><span><strong>按顺序规划</strong><small>进入「制定路线」，起飞前核对各航段用时、成本、收益与能量。</small></span></li><li><b>3</b><span><strong>抵达与中转</strong><small>到达最终目的地才结算；其他订单留在机上，也可卸下等待后续航班。</small></span></li></ol></section>
      <section className="help-card"><header><Icon name="map"/><h3>球面地图</h3></header><ul><li><strong>地图</strong><span>只用于浏览城市、查看机场和解锁航点，不会改动当前路线。</span></li><li><strong>操作</strong><span>拖动旋转，滚轮或双指缩放；方向键旋转，＋/－缩放，Home 定位当前飞机。</span></li><li><strong>可见范围</strong><span>球体背面的机场会隐藏；需要时仍可通过城市选择器访问全部机场。</span></li></ul></section>
      <section className="help-card"><header><Icon name="plane"/><h3>经营入口</h3></header><ul><li><strong>机队管理</strong><span>查看航班、切换飞机、改装、补充能量并管理周转。</span></li><li><strong>公司组织</strong><span>招聘员工、安排岗位与上级、培训并查看人员履历。</span></li><li><strong>公司经营中心</strong><span>领取目标与每日奖励，管理物流、服务、设施、研究、贸易和博物馆。</span></li></ul></section>
      <section className="help-card help-resources"><header><Icon name="ticket"/><h3>资源与结算</h3></header><dl><div><dt>运营资金</dt><dd>由订单交付和经营活动获得，用于航班、飞机、机场与服务。</dd></div><div><dt>点券</dt><dd>由有偿运输、目标、每日进度和博物馆捐赠等获得，用于人员与进阶经营。</dd></div><div><dt>时间</dt><dd>抵达按时间事件结算，不依赖动画回调；离线最多补算 8 小时。</dd></div></dl></section>
    </div>
    <aside className="help-rule-strip"><strong>请记住</strong><span>路线预览只读；每份订单只在最终目的地结算一次。机型和经营参数均为游戏化配置；球面地图不是导航或行政边界资料。</span></aside>
    <p className="muted-text">地图飞机：<a href="https://sketchfab.com/3d-models/low-poly-airliner-f06d488f08764e3ca26f2917d4053c69" target="_blank" rel="noreferrer">Low Poly Airliner · Mauro3D</a> · <a href={`${import.meta.env.BASE_URL}models/ATTRIBUTION.txt`} target="_blank" rel="noreferrer">CC BY 4.0 许可与修改说明</a></p>
  </div>;
}
