import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { GameViewport } from './ui/GameViewport.js';
import { App } from './ui/App.js';
import { SaveConflictGuard } from './ui/SaveConflictGuard.js';
import { I18nProvider } from './i18n/I18n.js';
import { PageStateProvider } from './ui/shell/PageState.js';
import { controller } from './runtime.js';
import './pwa.js';
import './ui/styles/index.js';
createRoot(document.getElementById('root')!).render(<StrictMode><I18nProvider><GameViewport><PageStateProvider><App /><SaveConflictGuard /></PageStateProvider></GameViewport></I18nProvider></StrictMode>);
void controller.start();
